#!/usr/bin/env sh

set -e

npm run build

cd dist

git init 
git add -A
git commit -m 'deploy'
git remote add origin git@gitee.com:senmao/geo-text-visualization.git
git push -f git@gitee.com:senmao/geo-text-visualization.git master

cd -